
final_project:	window.cpp window.hpp cabinet.cpp cabinet.hpp clock.cpp clock.hpp diceTable.cpp diceTable.hpp door.cpp door.hpp safe.cpp safe.hpp space.cpp space.hpp stove.cpp stove.hpp main.cpp floor.hpp floor.cpp quadLinkedList.hpp quadLinkedList.cpp item.cpp item.hpp
	g++ -std=c++0x -v -g window.cpp cabinet.cpp clock.cpp diceTable.cpp door.cpp safe.cpp space.cpp stove.cpp main.cpp floor.cpp quadLinkedList.cpp item.cpp -o final_project

claen:
	rm -f final_project *.o
